from __future__ import annotations

from typing import Any, Protocol


class SnapshotStore(Protocol):
    def insert_snapshot(self, payload: dict[str, Any]) -> None: ...
    def insert_event(self, severity: str, event_type: str, message: str, payload: dict[str, Any] | None = None) -> None: ...
    def status(self) -> dict[str, Any]: ...
    def close(self) -> None: ...
