[Service]
WorkingDirectory=/root/kinetics-grid-ems/northbound_ems_gateway
Environment=PYTHONPATH=/root/kinetics-grid-ems/northbound_ems_gateway/src
Environment=PYTHONUNBUFFERED=1
EnvironmentFile=-/etc/nb_ems_ugx_uploader.conf
