[Unit]
Wants=network-online.target ntpd.service kinetics-gateway.service
After=network-online.target ntpd.service kinetics-gateway.service
StartLimitIntervalSec=0

[Service]
ExecStartPre=/usr/local/sbin/bess-wait-for-valid-time.sh
TimeoutStartSec=1900
Restart=on-failure
RestartSec=60
