[Unit]
Requires=
After=
Wants=

After=ems-v3-eth1.service ems-v3-wifi.service cloudflared.service ems-v3-solis-link.service
Wants=ems-v3-eth1.service ems-v3-wifi.service cloudflared.service ems-v3-solis-link.service
